// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvykaxbmbakkcripgxmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2eWtheGJtYmFra2NyaXBneG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjgyNTIsImV4cCI6MjA3MTk0NDI1Mn0.EDVn37T3XjBbPvWjUaeA4tzfab5DQLzsis8Q52sGCQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});